[tool.poetry]
name = "cit-sci-traits"
version = "0.1.0"
description = ""
authors = ["Daniel Lusk <daniel.lusk@geosense.uni-freiburg.de>"]
readme = "README.md"
packages = [{include = "src"}]

[tool.poetry.dependencies]
python = ">3.11.0,<3.12"
python-dotenv = "^1.0.1"
ipykernel = "^6.29.3"
pandas = "^2.2.1"
rioxarray = "^0.15.1"
rasterio = "^1.3.9"
pyogrio = "^0.7.2"
pyyaml = "^6.0.1"
numpy = "^1.26.4"
matplotlib = "^3.8.3"
ipywidgets = "^8.1.2"
python-box = "~7"
seaborn = "^0.13.2"
cartopy = "^0.23.0"
geopandas = "^0.14.3"
pyarrow = "^16.0.0"
dask-geopandas = "^0.3.1"
dask = {extras = ["dataframe"], version = "^2024.4.2"}
joblib = "^1.4.2"
tqdm = "^4.66.4"
h3 = "^3.7.7"
pykrige = "^1.7.1"
utm = "^0.7.0"
bokeh = "^3.4.1"
setuptools = "^69.5.1"
wheel = "^0.43.0"
autogluon-tabular = {extras = ["all"], version = "^1.1.0"}
statsmodels = "^0.14.2"
tabulate = "^0.9.0"
scikit-learn = "~1.4"
rio-cogeo = "^5.3.6"
ease-grid = "^0.2"
verstack = "^4.1.4"

openpyxl = "^3.1.5"
simple-slurm = "^0.3.6"

[tool.poetry.group.cuda.dependencies]
torch = { version = "^2.0.0", source = "pytorch-cu121" }
# cudf-cu11 = { version = "24.10.*", source = "nvidia" }
# cuml-cu11 = { version = "24.10.*", source = "nvidia" }
# cupy-cuda11x = "^13.3.0"

# [tool.poetry.group.r.dependencies]
# rpy2 = "^3.5.16"

# [tool.poetry.group.dev.dependencies]
# pre-commit = "^3.6.2"
# pytest = "^8.1.1"
# pylint = "^3.1.0"
# pylint-pytest = "^1.1.7"
# pytest-mock = "^3.12.0"
# paramiko = "^3.4.0"
# earthengine-api = "^1.4.5"
# ruff = "^0.14.2"

# [tool.poetry.group.profiling.dependencies]
# line_profiler = "^4"
# scalene = "^1.5.51"

# [tool.poetry.group.analysis.dependencies]
# adjusttext = "^1.3.0"
# python-docx = "^1.1.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[[tool.poetry.source]]
name = "nvidia"
url = "https://pypi.nvidia.com"
priority = "supplemental"

[[tool.poetry.source]]
name = "pytorch-cu121"
url = "https://download.pytorch.org/whl/cu121"
priority = "explicit"